language: cpp

before_install:
  - echo $TRAVIS_BUILD_DIR
  - echo $HOME
  - wget http://dev-www.libreoffice.org/src/cppunit-1.13.2.tar.gz
  - tar -xvzf cppunit-1.13.2.tar.gz
  - cd cppunit-1.13.2
  - ./configure --prefix=$TRAVIS_BUILD_DIR
  - make
  - make install
  - ls $TRAVIS_BUILD_DIR/include/cppunit
  - ls $TRAVIS_BUILD_DIR/lib
  - cd ..
  - export CPLUS_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$CPLUS_INCLUDE_PATH
  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
  
script:
  - make test